############# English navigation ##############

# main menu
[[main]]
name = "首頁"
url = "/"
weight = 1

[[main]]
name = "關於"
url = "/about"
weight = 2

[[main]]
name = "部落格"
url = "/blog"
weight = 3

[[main]]
name = "下載資源"
url = "/resource"
weight = 4


# footer menu
[[footer]]
name = "隱私權政策"
url = "/privacy-policy"
weight = 1

[[footer]]
name = "免責聲明"
url = "/affiliate-disclosure"
weight = 2

[[footer]]
name = "著作權聲明"
url = "/copyright"
weight = 3
